# Set logo key. Use Mod1 for Alt.
set $mod Mod4

# Set vim-like direction keys
set $left h
set $down j
set $up k
set $right l

# Set workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# System app
set $term wezterm
set $browser_work firefox -p Work
set $browser_personal firefox -p Personal
set $media flatpak run com.spotify.Client
set $obsidian flatpak run md.obsidian.Obsidian
set $pdf zathura
set $office flatpak run org.onlyoffice.desktopeditors
set $refmanager gtk-launch zotero.desktop
set $social exec zapzap

set $lockscreen swaylock
set $powermenu wlogout

# App launcher : rofi
set $rofi_drun rofi -show drun -disable-history -show-icons
set $rofi_run rofi -show run -disable-history
set $rofi_windows rofi -show window -show-icons
set $rofi_emoji rofi -modi "emoji:rofimoji" -show emoji

# Screenshot
set $full_screenshot grim ~/Pictures/screenshots/$(date +'%Y-%m-%d_%H-%M-%S.png') && notify-send -e "Screenshot taken"
set $edit_screenshot grim - | satty --no-window-decoration --filename - --output-filename ~/Pictures/screenshots/$(date '+%Y-%m-%d_%H-%M-%S.png')
