# Assign programs to workspace
# Workspace 1
assign [app_id="(?i).*foot.*"] $ws1
assign [app_id="(?i).*wezterm.*"] $ws1
assign [app_id="(?i).*rstudio.*"] $ws1
assign [class="(?i).*obsidian.*"] $ws1

# Workspace 2
assign [app_id="(?i).*firefox.*"] $ws2

# Workspace 3
assign [app_id="(?i).*office.*"] $ws3
assign [class="ONLYOFFICE"] $ws3

# Workspace 4

# Workspace 5
assign [app_id="(?i).*gimp.*"] $ws5
assign [app_id="(?i).*inkscape.*"] $ws5

# Workspace 6

# Workspace 7

# Workspace 8
assign [app_id="(?i).*spotify.*"] $ws8
assign [class="vlc"] $ws8

# Workspace 9
assign [app_id="(?i).*zapzap.*"] $ws9
assign [class="(?i).*zoom.*"] $ws9

# Workspace 10
assign [app_id="(?i).*zotero.*"] $ws10
assign [app_id="(?i).*zathura.*"] $ws10
assign [app_id="(?i).*okular.*"] $ws10

# Assign workspace to monitor
workspace $ws1 output eDP-1
workspace $ws3 output eDP-1
workspace $ws5 output eDP-1
workspace $ws8 output eDP-1
workspace $ws9 output eDP-1
workspace $ws10 output HDMI-A-1
