# Input
input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll enabled
    middle_emulation enabled
}

input 11145:67:UGREEN_Receiver__Mouse {
    natural_scroll enabled
}

# Output
# Kanshi manage our output
